project:
  type: website

website:
  title: "biostat777-intro-Koko-Hall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - ExampleAnalysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

