project:
  type: website

website:
  title: "Koko Hall, B.S."
  navbar:
    collapse: false
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: ExampleAnalysis.qmd
        text: Example Analysis


format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

