---
title: "Bio"
about:
  template: marquee

---

:::{#hero-heading}
Koko has research interests in epigenetics and neurodevelopmental disorders. Her current research focuses on evaluating the performance of epigenetic clocks in pediatric populations when measuring the rate of biological aging. She has skills in statistical analysis using R, epidemiologic methods, the implementation of randomized controlled trials, and regulatory work involving the IRB and FDA.

## Education
Johns Hopkins Bloomberg School of Public Health | Baltimore, MD

ScM in Genetic Epidemiology | August 2023-Present

University of Washington | Seattle, WA

B.S. in Psychology (Honors Program) | September 2015 - March 2019

## Experience
National Human Genomics Research Institute | Immersive Summer Program for Research in Genomics (iSPRinG) Intern | June 2024-August 2024

Johns Hopkins Bloomberg School of Public Health | Graduate Research Assistant | November 2023 - Present

Seattle Children’s Hospital, Department of Neurosurgery | Clinical Research Coordinator III | July 2021-August 2023

## Publications
Lundy, P., Barkley, A., Rahman, A. K. M. F… **Hall, K**., … Rocque, B. G. (2024). Pediatric CSF diversion procedures for treatment of hydrocephalus during the COVID-19 pandemic. Journal of neurosurgery. Pediatrics, 1–7. Advance online publication. https://doi.org/10.3171/2024.7.PEDS24249 

Dewan, M. C., Isaacs, A. M., Cools, M. J… **Hall, K**… Hydrocephalus Clinical Research Network (2023). Treatment of hydrocephalus following posterior fossa tumor resection: a multicenter collaboration from the Hydrocephalus Clinical Research Network. Journal of neuro-oncology, 163(1), 123–132. https://doi.org/10.1007/s11060-023-04316-4

## Presentations 
**Hall, K.**, He, Z., Ladd-Acosta, C., (September 2024) Evaluation of Pace of Epigenetic Aging in Early Childhood [Poster presentation at the Maryland Genetics, Epidemiology and Medicine (MD-GEM) Research Day in Baltimore, MD]

**Hall, K.**, Sugden, N., Gunter, C., (August 2024) Exploring Stigmatizing Language in NIH-Funded Genomic and Genetics Abstracts [Poster presentation at the NIH Summer Poster Day in Bethesda, MD]

**Hall, L.T.**, Sargent, C.L., Ganz, W.R., Eichler, E.E., Bernier, R. Webb, S.J., Hudac, C.M. (May 2021) Resting state EEG Spectral Differences in SCN2A, ASD, and TD Individuals [Poster presentation at the International Society for Autism Research (INSAR) annual meeting in Boston, MA] (Conference online)

Ganz, W.R., **Hall, L.T.**, Sargent, C.L., Wadhwani, K., Earl, R.K., Eichler, E.E., Bernier, R.A., Webb, S.J., & Hudac, C.M. (May 2020). Differences In Resting State Alpha Power between LGDM, Idiopathic ASD, and Typically Developing Individuals [Poster presentation at the International Society for Autism Research (INSAR) annual meeting in Seattle, WA] (Conference online)

**Hall, L.**, Kurtz-Nelson, E., Earl., R, Wallace, A., Eichler, E., Bernier, R. (April 2020) Maternal Health Complications, ASD Diagnostic Prevalence, and Symptoms Among Individuals with Likely Gene Disrupting Mutations. [Poster presentation at the Gatlinburg Conference on Research and Theory in Intellectual and Developmental Disabilities in San Diego, CA] (Conference canceled due to Covid-19 pandemic) 
										                        
**Hall, L.**, Gerdts, J., Bernier, R. (May 2019) Maternal Thyroid Dysfunction, Likely Gene Disrupting Mutations, and the Impact on ASD Severity [Poster presentations at the UW Undergraduate Research Symposium and Psychology Honors Symposium in Seattle, WA] 

