project:
  type: website

website:
  title: "halloween-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - favecandy.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

execute: 
  freeze: auto

editor: visual

